# Generated by Django 4.2.7 on 2023-11-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_myuser_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='password',
            field=models.CharField(default='', max_length=16),
        ),
    ]
