# Generated by Django 4.2.7 on 2023-11-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_myuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='password',
        ),
    ]
